---
# tasks file for jenkins
- name: install java
  apt:
    name: openjdk-8-jre-headless
    state: present
    update_cache: yes

- name: import jenkins key
  shell: "wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | apt-key add -"

- name: configure jenkins repository
  shell: "sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'"

- name: install jenkins
  apt: name=jenkins update_cache=yes force_apt_get=yes


