---
# tasks file for mysql
- name: install MySql
  apt: name={{ item }} update_cache=yes state=latest
  loop: [ 'mysql-server', 'python3-pymysql' ]

- name: create database
  community.mysql.mysql_db:
     name: "{{ mysql_db }}"
     state: present
     login_unix_socket: /var/run/mysqld/mysqld.sock


- name: Create MySQL user
  community.mysql.mysql_user:
     name: "{{ mysql_user }}"
     password: "{{ mysql_password }}"
     priv: "{{ mysql_db }}.*:ALL,GRANT"
     state: present
     login_unix_socket: /var/run/mysqld/mysqld.sock


