---
- name: launch site on LAMP
  hosts: LAMP
  become: yes
  roles:
    - apache
    - mysql
    - NoviNano
    - php


- name: launch jenkins in vm
  hosts: jenkins
  become: yes
  roles:
    - jenkins
