---
# tasks file for NoviNano
- name: install prerequisites
  apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

- name: download archive
  get_url:
    url: https://github.com/mplesha/NoviNano/releases/download/v1.0/20180706_novinano_mt_b2a03d4e0cbc53e87026180706071957_archive.zip
    dest: /var/www/{{ http_host }}/

- name: download installer
  get_url:
    url: https://github.com/mplesha/NoviNano/releases/download/v1.0/20180706_novinano_mt_b2a03d4e0cbc53e87026180706071957_installer.php
    dest: ~/

- name: rename installer.php
  command: mv ~/20180706_novinano_mt_b2a03d4e0cbc53e87026180706071957_installer.php /var/www/{{ http_host }}/installer.php

- name: set rights for site folder
  file:
     path: /var/www/{{ http_host }}
     state: directory
     recurse: yes
     owner: www-data
     group: www-data

- name: Set permissions for directories
  shell: "/usr/bin/find /var/www/{{ http_host }} -type d -exec chmod 750 {} \\;"

- name: Set permissions for files
  shell: "/usr/bin/find /var/www/{{ http_host }} -type f -exec chmod 640 {} \\;"

- name: remove index.html
  file:
    path: /var/www/html/index.html
    state: absent
